"""Create the complete initial application schema.

Revision ID: 20260723_0001
Revises:
Create Date: 2026-07-23
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20260723_0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create PostgreSQL enum types, tables, constraints, and indexes."""
    bind = op.get_bind()
    postgresql.ENUM(
        "queued",
        "running",
        "waiting_for_user",
        "completed",
        "failed",
        "cancelled",
        name="agent_run_status",
    ).create(bind, checkfirst=True)
    postgresql.ENUM(
        "pending", "approved", "rejected", "expired", "consumed", name="approval_status"
    ).create(bind, checkfirst=True)
    postgresql.ENUM(
        "pending",
        "confirmed",
        "cancelled",
        "completed",
        "failed",
        name="booking_status",
    ).create(bind, checkfirst=True)
    postgresql.ENUM(
        "flight",
        "lodging",
        "rail",
        "vehicle",
        "activity",
        "transfer",
        "other",
        name="booking_type",
    ).create(bind, checkfirst=True)
    postgresql.ENUM(
        "economy", "premium_economy", "business", "first", name="cabin_class"
    ).create(bind, checkfirst=True)
    postgresql.ENUM("active", "archived", name="conversation_status").create(
        bind, checkfirst=True
    )
    postgresql.ENUM(
        "flight",
        "lodging",
        "rail",
        "transfer",
        "activity",
        "meal",
        "note",
        name="itinerary_item_kind",
    ).create(bind, checkfirst=True)
    postgresql.ENUM(
        "draft",
        "proposed",
        "accepted",
        "superseded",
        "archived",
        name="itinerary_status",
    ).create(bind, checkfirst=True)
    postgresql.ENUM(
        "preference", "fact", "episodic", "summary", name="memory_kind"
    ).create(bind, checkfirst=True)
    postgresql.ENUM("user", "assistant", "system", "tool", name="message_role").create(
        bind, checkfirst=True
    )
    postgresql.ENUM(
        "pending", "processing", "published", "failed", name="outbox_status"
    ).create(bind, checkfirst=True)
    postgresql.ENUM(
        "authorization", "capture", "refund", "void", name="payment_kind"
    ).create(bind, checkfirst=True)
    postgresql.ENUM(
        "pending", "succeeded", "failed", "cancelled", name="payment_status"
    ).create(bind, checkfirst=True)
    postgresql.ENUM(
        "active", "revoked", "expired", "error", name="provider_connection_status"
    ).create(bind, checkfirst=True)
    postgresql.ENUM(
        "pending", "running", "succeeded", "failed", "denied", name="tool_call_status"
    ).create(bind, checkfirst=True)
    postgresql.ENUM("read", "write", "financial", name="tool_risk").create(
        bind, checkfirst=True
    )
    postgresql.ENUM(
        "draft",
        "planning",
        "booked",
        "in_progress",
        "completed",
        "cancelled",
        "archived",
        name="trip_status",
    ).create(bind, checkfirst=True)
    postgresql.ENUM("active", "suspended", "deleted", name="user_status").create(
        bind, checkfirst=True
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outbox_events",
        sa.Column("aggregate_type", sa.String(length=120), nullable=False),
        sa.Column("aggregate_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=160), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "pending",
                "processing",
                "published",
                "failed",
                name="outbox_status",
                create_type=False,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_events")),
    )
    op.create_index(
        "ix_outbox_events_aggregate",
        "outbox_events",
        ["aggregate_type", "aggregate_id"],
        unique=False,
    )
    op.create_index(
        "ix_outbox_events_dispatch",
        "outbox_events",
        ["status", "available_at", "created_at"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("auth_issuer", sa.String(length=255), nullable=False),
        sa.Column("auth_subject", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "active", "suspended", "deleted", name="user_status", create_type=False
            ),
            server_default="active",
            nullable=False,
        ),
        sa.Column("last_login_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "email = lower(email)", name=op.f("ck_users_email_lowercase")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint(
            "auth_issuer", "auth_subject", name="uq_users_auth_identity"
        ),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_index(
        "ix_users_status_created_at", "users", ["status", "created_at"], unique=False
    )
    op.create_table(
        "audit_events",
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("actor_subject", sa.String(length=255), nullable=False),
        sa.Column("action", sa.String(length=160), nullable=False),
        sa.Column("resource_type", sa.String(length=120), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=True),
        sa.Column("outcome", sa.String(length=80), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_audit_events_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index(
        "ix_audit_events_resource_created",
        "audit_events",
        ["resource_type", "resource_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_audit_events_user_created",
        "audit_events",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "preferences",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("home_airport", sa.String(length=3), nullable=True),
        sa.Column(
            "default_currency",
            sa.String(length=3),
            server_default="USD",
            nullable=False,
        ),
        sa.Column(
            "locale", sa.String(length=35), server_default="en-US", nullable=False
        ),
        sa.Column(
            "timezone", sa.String(length=64), server_default="UTC", nullable=False
        ),
        sa.Column(
            "cabin_class",
            postgresql.ENUM(
                "economy",
                "premium_economy",
                "business",
                "first",
                name="cabin_class",
                create_type=False,
            ),
            server_default="economy",
            nullable=False,
        ),
        sa.Column("max_layovers", sa.Integer(), nullable=True),
        sa.Column(
            "prefers_direct", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column(
            "dietary_requirements",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "accessibility_requirements",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "default_currency ~ '^[A-Z]{3}$'",
            name=op.f("ck_preferences_currency_iso_format"),
        ),
        sa.CheckConstraint(
            "home_airport IS NULL OR home_airport ~ '^[A-Z]{3}$'",
            name=op.f("ck_preferences_home_airport_iata_format"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(accessibility_requirements) = 'array'",
            name=op.f("ck_preferences_accessibility_requirements_array"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(dietary_requirements) = 'array'",
            name=op.f("ck_preferences_dietary_requirements_array"),
        ),
        sa.CheckConstraint(
            "max_layovers IS NULL OR max_layovers >= 0",
            name=op.f("ck_preferences_nonnegative_max_layovers"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_preferences_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_preferences")),
        sa.UniqueConstraint("user_id", name=op.f("uq_preferences_user_id")),
    )
    op.create_table(
        "provider_connections",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=120), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "active",
                "revoked",
                "expired",
                "error",
                name="provider_connection_status",
                create_type=False,
            ),
            server_default="active",
            nullable=False,
        ),
        sa.Column("vault_secret_ref", sa.String(length=500), nullable=False),
        sa.Column("scopes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_provider_connections_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_connections")),
    )
    op.create_index(
        "ix_provider_connections_status_expiry",
        "provider_connections",
        ["status", "expires_at"],
        unique=False,
    )
    op.create_index(
        "uq_provider_connections_user_provider",
        "provider_connections",
        ["user_id", "provider"],
        unique=True,
    )
    op.create_table(
        "trips",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("origin_code", sa.String(length=3), nullable=True),
        sa.Column("destination_summary", sa.Text(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "draft",
                "planning",
                "booked",
                "in_progress",
                "completed",
                "cancelled",
                "archived",
                name="trip_status",
                create_type=False,
            ),
            server_default="draft",
            nullable=False,
        ),
        sa.Column("party_size", sa.Integer(), server_default="1", nullable=False),
        sa.Column("budget_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column(
            "currency", sa.String(length=3), server_default="USD", nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "currency ~ '^[A-Z]{3}$'", name=op.f("ck_trips_currency_iso_format")
        ),
        sa.CheckConstraint(
            "origin_code IS NULL OR origin_code ~ '^[A-Z]{3}$'",
            name=op.f("ck_trips_origin_iata_format"),
        ),
        sa.CheckConstraint(
            "budget_amount IS NULL OR budget_amount >= 0",
            name=op.f("ck_trips_nonnegative_budget"),
        ),
        sa.CheckConstraint(
            "end_date IS NULL OR start_date IS NULL OR end_date >= start_date",
            name=op.f("ck_trips_valid_date_range"),
        ),
        sa.CheckConstraint("party_size > 0", name=op.f("ck_trips_positive_party_size")),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_trips_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trips")),
    )
    op.create_index(
        "ix_trips_user_status_start",
        "trips",
        ["user_id", "status", "start_date"],
        unique=False,
    )
    op.create_table(
        "conversations",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("trip_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=160), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "active", "archived", name="conversation_status", create_type=False
            ),
            server_default="active",
            nullable=False,
        ),
        sa.Column("last_message_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
            name=op.f("fk_conversations_trip_id_trips"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_conversations_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
    )
    op.create_index(
        "ix_conversations_trip_updated",
        "conversations",
        ["trip_id", "updated_at"],
        unique=False,
    )
    op.create_index(
        "ix_conversations_user_updated",
        "conversations",
        ["user_id", "updated_at"],
        unique=False,
    )
    op.create_table(
        "travelers",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("trip_id", sa.Uuid(), nullable=False),
        sa.Column("given_name", sa.String(length=120), nullable=False),
        sa.Column("family_name", sa.String(length=120), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column(
            "loyalty_programs", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "date_of_birth IS NULL OR date_of_birth <= CURRENT_DATE",
            name=op.f("ck_travelers_birth_date_not_future"),
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
            name=op.f("fk_travelers_trip_id_trips"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_travelers_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_travelers")),
    )
    op.create_index(
        "ix_travelers_trip_created",
        "travelers",
        ["trip_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "agent_runs",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("trip_id", sa.Uuid(), nullable=True),
        sa.Column("parent_run_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "queued",
                "running",
                "waiting_for_user",
                "completed",
                "failed",
                "cancelled",
                name="agent_run_status",
                create_type=False,
            ),
            server_default="queued",
            nullable=False,
        ),
        sa.Column("graph_name", sa.String(length=120), nullable=False),
        sa.Column("graph_version", sa.String(length=64), nullable=False),
        sa.Column("model_name", sa.String(length=160), nullable=True),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column(
            "input_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "output_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("queued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("prompt_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "completion_tokens", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column("estimated_cost", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "completed_at IS NULL OR started_at IS NULL OR completed_at >= started_at",
            name=op.f("ck_agent_runs_valid_execution_window"),
        ),
        sa.CheckConstraint(
            "estimated_cost IS NULL OR estimated_cost >= 0",
            name=op.f("ck_agent_runs_nonnegative_cost"),
        ),
        sa.CheckConstraint(
            "prompt_tokens >= 0 AND completion_tokens >= 0",
            name=op.f("ck_agent_runs_nonnegative_tokens"),
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_agent_runs_conversation_id_conversations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["parent_run_id"],
            ["agent_runs.id"],
            name=op.f("fk_agent_runs_parent_run_id_agent_runs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
            name=op.f("fk_agent_runs_trip_id_trips"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_agent_runs_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_runs")),
        sa.UniqueConstraint(
            "user_id",
            "idempotency_key",
            name="uq_agent_runs_user_idempotency",
        ),
    )
    op.create_index(
        "ix_agent_runs_conversation_created",
        "agent_runs",
        ["conversation_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_agent_runs_status_created",
        "agent_runs",
        ["status", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_agent_runs_trip_created",
        "agent_runs",
        ["trip_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "itineraries",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("trip_id", sa.Uuid(), nullable=False),
        sa.Column("agent_run_id", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "draft",
                "proposed",
                "accepted",
                "superseded",
                "archived",
                name="itinerary_status",
                create_type=False,
            ),
            server_default="draft",
            nullable=False,
        ),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("summary", sa.String(length=2000), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("version > 0", name=op.f("ck_itineraries_positive_version")),
        sa.ForeignKeyConstraint(
            ["agent_run_id"],
            ["agent_runs.id"],
            name=op.f("fk_itineraries_agent_run_id_agent_runs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
            name=op.f("fk_itineraries_trip_id_trips"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_itineraries_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_itineraries")),
    )
    op.create_index(
        "ix_itineraries_trip_status", "itineraries", ["trip_id", "status"], unique=False
    )
    op.create_index(
        "uq_itineraries_trip_version",
        "itineraries",
        ["trip_id", "version"],
        unique=True,
    )
    op.create_table(
        "messages",
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("agent_run_id", sa.Uuid(), nullable=True),
        sa.Column("parent_message_id", sa.Uuid(), nullable=True),
        sa.Column("sequence_number", sa.Integer(), nullable=False),
        sa.Column(
            "role",
            postgresql.ENUM(
                "user",
                "assistant",
                "system",
                "tool",
                name="message_role",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column(
            "content_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("token_count", sa.Integer(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=128), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "content IS NOT NULL OR content_json IS NOT NULL",
            name=op.f("ck_messages_content_present"),
        ),
        sa.CheckConstraint(
            "sequence_number > 0", name=op.f("ck_messages_positive_sequence")
        ),
        sa.CheckConstraint(
            "token_count IS NULL OR token_count >= 0",
            name=op.f("ck_messages_nonnegative_token_count"),
        ),
        sa.ForeignKeyConstraint(
            ["agent_run_id"],
            ["agent_runs.id"],
            name=op.f("fk_messages_agent_run_id_agent_runs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_messages_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["parent_message_id"],
            ["messages.id"],
            name=op.f("fk_messages_parent_message_id_messages"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
        sa.UniqueConstraint(
            "conversation_id",
            "idempotency_key",
            name="uq_messages_conversation_idempotency",
        ),
        sa.UniqueConstraint(
            "conversation_id",
            "sequence_number",
            name="uq_messages_conversation_sequence",
        ),
    )
    op.create_index("ix_messages_agent_run", "messages", ["agent_run_id"], unique=False)
    op.create_index(
        "ix_messages_conversation_created",
        "messages",
        ["conversation_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "tool_calls",
        sa.Column("agent_run_id", sa.Uuid(), nullable=False),
        sa.Column("sequence_number", sa.Integer(), nullable=False),
        sa.Column("mcp_server", sa.String(length=160), nullable=False),
        sa.Column("tool_name", sa.String(length=160), nullable=False),
        sa.Column(
            "risk",
            postgresql.ENUM(
                "read", "write", "financial", name="tool_risk", create_type=False
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "pending",
                "running",
                "succeeded",
                "failed",
                "denied",
                name="tool_call_status",
                create_type=False,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column(
            "request_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "response_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "completed_at IS NULL OR started_at IS NULL OR completed_at >= started_at",
            name=op.f("ck_tool_calls_valid_execution_window"),
        ),
        sa.CheckConstraint(
            "sequence_number > 0", name=op.f("ck_tool_calls_positive_sequence")
        ),
        sa.ForeignKeyConstraint(
            ["agent_run_id"],
            ["agent_runs.id"],
            name=op.f("fk_tool_calls_agent_run_id_agent_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tool_calls")),
        sa.UniqueConstraint(
            "agent_run_id", "sequence_number", name="uq_tool_calls_run_sequence"
        ),
        sa.UniqueConstraint("idempotency_key", name="uq_tool_calls_idempotency"),
    )
    op.create_index(
        "ix_tool_calls_server_tool_created",
        "tool_calls",
        ["mcp_server", "tool_name", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_tool_calls_status_created",
        "tool_calls",
        ["status", "created_at"],
        unique=False,
    )
    op.create_table(
        "approvals",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("agent_run_id", sa.Uuid(), nullable=False),
        sa.Column("tool_call_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "pending",
                "approved",
                "rejected",
                "expired",
                "consumed",
                name="approval_status",
                create_type=False,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column(
            "risk",
            postgresql.ENUM(
                "read", "write", "financial", name="tool_risk", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("action_summary", sa.String(length=500), nullable=False),
        sa.Column(
            "proposed_action", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decision_reason", sa.String(length=1000), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "decided_at IS NULL OR decided_at >= created_at",
            name=op.f("ck_approvals_decision_after_creation"),
        ),
        sa.CheckConstraint("version > 0", name=op.f("ck_approvals_positive_version")),
        sa.ForeignKeyConstraint(
            ["agent_run_id"],
            ["agent_runs.id"],
            name=op.f("fk_approvals_agent_run_id_agent_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tool_call_id"],
            ["tool_calls.id"],
            name=op.f("fk_approvals_tool_call_id_tool_calls"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_approvals_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approvals")),
    )
    op.create_index(
        "ix_approvals_expires", "approvals", ["status", "expires_at"], unique=False
    )
    op.create_index(
        "ix_approvals_run_status", "approvals", ["agent_run_id", "status"], unique=False
    )
    op.create_index(
        "ix_approvals_user_status_created",
        "approvals",
        ["user_id", "status", "created_at"],
        unique=False,
    )
    op.create_table(
        "bookings",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("trip_id", sa.Uuid(), nullable=False),
        sa.Column("source_tool_call_id", sa.Uuid(), nullable=True),
        sa.Column("provider", sa.String(length=120), nullable=False),
        sa.Column("provider_booking_id", sa.String(length=160), nullable=True),
        sa.Column(
            "booking_type",
            postgresql.ENUM(
                "flight",
                "lodging",
                "rail",
                "vehicle",
                "activity",
                "transfer",
                "other",
                name="booking_type",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "pending",
                "confirmed",
                "cancelled",
                "completed",
                "failed",
                name="booking_status",
                create_type=False,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("booked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancellation_deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "currency ~ '^[A-Z]{3}$'", name=op.f("ck_bookings_currency_iso_format")
        ),
        sa.CheckConstraint("amount >= 0", name=op.f("ck_bookings_nonnegative_amount")),
        sa.CheckConstraint(
            "end_at IS NULL OR start_at IS NULL OR end_at >= start_at",
            name=op.f("ck_bookings_valid_service_window"),
        ),
        sa.ForeignKeyConstraint(
            ["source_tool_call_id"],
            ["tool_calls.id"],
            name=op.f("fk_bookings_source_tool_call_id_tool_calls"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
            name=op.f("fk_bookings_trip_id_trips"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_bookings_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bookings")),
        sa.UniqueConstraint(
            "provider", "provider_booking_id", name="uq_bookings_provider_reference"
        ),
    )
    op.create_index("ix_bookings_start", "bookings", ["start_at"], unique=False)
    op.create_index(
        "ix_bookings_trip_status", "bookings", ["trip_id", "status"], unique=False
    )
    op.create_index(
        "ix_bookings_user_status_created",
        "bookings",
        ["user_id", "status", "created_at"],
        unique=False,
    )
    op.create_table(
        "itinerary_items",
        sa.Column("itinerary_id", sa.Uuid(), nullable=False),
        sa.Column("source_tool_call_id", sa.Uuid(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            postgresql.ENUM(
                "flight",
                "lodging",
                "rail",
                "transfer",
                "activity",
                "meal",
                "note",
                name="itinerary_item_kind",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("location", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "position > 0", name=op.f("ck_itinerary_items_positive_position")
        ),
        sa.ForeignKeyConstraint(
            ["itinerary_id"],
            ["itineraries.id"],
            name=op.f("fk_itinerary_items_itinerary_id_itineraries"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_tool_call_id"],
            ["tool_calls.id"],
            name=op.f("fk_itinerary_items_source_tool_call_id_tool_calls"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_itinerary_items")),
    )
    op.create_index(
        "ix_itinerary_items_time",
        "itinerary_items",
        ["itinerary_id", "starts_at"],
        unique=False,
    )
    op.create_index(
        "uq_itinerary_items_itinerary_position",
        "itinerary_items",
        ["itinerary_id", "position"],
        unique=True,
    )
    op.create_table(
        "memories",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("trip_id", sa.Uuid(), nullable=True),
        sa.Column("conversation_id", sa.Uuid(), nullable=True),
        sa.Column("source_message_id", sa.Uuid(), nullable=True),
        sa.Column(
            "kind",
            postgresql.ENUM(
                "preference",
                "fact",
                "episodic",
                "summary",
                name="memory_kind",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("embedding_model", sa.String(length=160), nullable=True),
        sa.Column(
            "confidence",
            sa.Numeric(precision=4, scale=3),
            server_default="1",
            nullable=False,
        ),
        sa.Column(
            "importance",
            sa.Numeric(precision=4, scale=3),
            server_default="0.5",
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_accessed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1",
            name=op.f("ck_memories_confidence_unit_interval"),
        ),
        sa.CheckConstraint(
            "importance >= 0 AND importance <= 1",
            name=op.f("ck_memories_importance_unit_interval"),
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_memories_conversation_id_conversations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_message_id"],
            ["messages.id"],
            name=op.f("fk_memories_source_message_id_messages"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
            name=op.f("fk_memories_trip_id_trips"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_memories_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memories")),
    )
    op.create_index(
        "ix_memories_conversation", "memories", ["conversation_id"], unique=False
    )
    op.create_index(
        "ix_memories_expires_at",
        "memories",
        ["expires_at"],
        unique=False,
        postgresql_where=sa.text("expires_at IS NOT NULL"),
    )
    op.create_index(
        "ix_memories_trip_kind", "memories", ["trip_id", "kind"], unique=False
    )
    op.create_index(
        "ix_memories_user_kind_created",
        "memories",
        ["user_id", "kind", "created_at"],
        unique=False,
    )
    op.create_table(
        "payments",
        sa.Column("booking_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=120), nullable=False),
        sa.Column("provider_payment_id", sa.String(length=160), nullable=True),
        sa.Column(
            "kind",
            postgresql.ENUM(
                "authorization",
                "capture",
                "refund",
                "void",
                name="payment_kind",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "pending",
                "succeeded",
                "failed",
                "cancelled",
                name="payment_status",
                create_type=False,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "currency ~ '^[A-Z]{3}$'", name=op.f("ck_payments_currency_iso_format")
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_payments_positive_amount")),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
            name=op.f("fk_payments_booking_id_bookings"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_payments_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
        sa.UniqueConstraint("idempotency_key", name="uq_payments_idempotency"),
        sa.UniqueConstraint(
            "provider", "provider_payment_id", name="uq_payments_provider_reference"
        ),
    )
    op.create_index(
        "ix_payments_booking_created",
        "payments",
        ["booking_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_payments_user_status_created",
        "payments",
        ["user_id", "status", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop schema objects in reverse dependency order."""
    bind = op.get_bind()
    op.drop_index("ix_payments_user_status_created", table_name="payments")
    op.drop_index("ix_payments_booking_created", table_name="payments")
    op.drop_table("payments")
    op.drop_index("ix_memories_user_kind_created", table_name="memories")
    op.drop_index("ix_memories_trip_kind", table_name="memories")
    op.drop_index("ix_memories_expires_at", table_name="memories")
    op.drop_index("ix_memories_conversation", table_name="memories")
    op.drop_table("memories")
    op.drop_index("uq_itinerary_items_itinerary_position", table_name="itinerary_items")
    op.drop_index("ix_itinerary_items_time", table_name="itinerary_items")
    op.drop_table("itinerary_items")
    op.drop_index("ix_bookings_user_status_created", table_name="bookings")
    op.drop_index("ix_bookings_trip_status", table_name="bookings")
    op.drop_index("ix_bookings_start", table_name="bookings")
    op.drop_table("bookings")
    op.drop_index("ix_approvals_user_status_created", table_name="approvals")
    op.drop_index("ix_approvals_run_status", table_name="approvals")
    op.drop_index("ix_approvals_expires", table_name="approvals")
    op.drop_table("approvals")
    op.drop_index("ix_tool_calls_status_created", table_name="tool_calls")
    op.drop_index("ix_tool_calls_server_tool_created", table_name="tool_calls")
    op.drop_table("tool_calls")
    op.drop_index("ix_messages_conversation_created", table_name="messages")
    op.drop_index("ix_messages_agent_run", table_name="messages")
    op.drop_table("messages")
    op.drop_index("uq_itineraries_trip_version", table_name="itineraries")
    op.drop_index("ix_itineraries_trip_status", table_name="itineraries")
    op.drop_table("itineraries")
    op.drop_index("ix_agent_runs_trip_created", table_name="agent_runs")
    op.drop_index("ix_agent_runs_status_created", table_name="agent_runs")
    op.drop_index("ix_agent_runs_conversation_created", table_name="agent_runs")
    op.drop_table("agent_runs")
    op.drop_index("ix_travelers_trip_created", table_name="travelers")
    op.drop_table("travelers")
    op.drop_index("ix_conversations_user_updated", table_name="conversations")
    op.drop_index("ix_conversations_trip_updated", table_name="conversations")
    op.drop_table("conversations")
    op.drop_index("ix_trips_user_status_start", table_name="trips")
    op.drop_table("trips")
    op.drop_index(
        "uq_provider_connections_user_provider", table_name="provider_connections"
    )
    op.drop_index(
        "ix_provider_connections_status_expiry", table_name="provider_connections"
    )
    op.drop_table("provider_connections")
    op.drop_table("preferences")
    op.drop_index("ix_audit_events_user_created", table_name="audit_events")
    op.drop_index("ix_audit_events_resource_created", table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index("ix_users_status_created_at", table_name="users")
    op.drop_table("users")
    op.drop_index("ix_outbox_events_dispatch", table_name="outbox_events")
    op.drop_index("ix_outbox_events_aggregate", table_name="outbox_events")
    op.drop_table("outbox_events")
    postgresql.ENUM(name="user_status").drop(bind, checkfirst=True)
    postgresql.ENUM(name="trip_status").drop(bind, checkfirst=True)
    postgresql.ENUM(name="tool_risk").drop(bind, checkfirst=True)
    postgresql.ENUM(name="tool_call_status").drop(bind, checkfirst=True)
    postgresql.ENUM(name="provider_connection_status").drop(bind, checkfirst=True)
    postgresql.ENUM(name="payment_status").drop(bind, checkfirst=True)
    postgresql.ENUM(name="payment_kind").drop(bind, checkfirst=True)
    postgresql.ENUM(name="outbox_status").drop(bind, checkfirst=True)
    postgresql.ENUM(name="message_role").drop(bind, checkfirst=True)
    postgresql.ENUM(name="memory_kind").drop(bind, checkfirst=True)
    postgresql.ENUM(name="itinerary_status").drop(bind, checkfirst=True)
    postgresql.ENUM(name="itinerary_item_kind").drop(bind, checkfirst=True)
    postgresql.ENUM(name="conversation_status").drop(bind, checkfirst=True)
    postgresql.ENUM(name="cabin_class").drop(bind, checkfirst=True)
    postgresql.ENUM(name="booking_type").drop(bind, checkfirst=True)
    postgresql.ENUM(name="booking_status").drop(bind, checkfirst=True)
    postgresql.ENUM(name="approval_status").drop(bind, checkfirst=True)
    postgresql.ENUM(name="agent_run_status").drop(bind, checkfirst=True)
